# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll Faces
email: hello@jekyllfaces.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll is a great blogging platform, but to make it really shine, you need
  to make some tweaks. We’ve made those tweaks, and we’ve done so in such a
  way as to avoid using plugins, so your site can easily be hosted on GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jekyllfaces.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: groundh0g
github_username:  groundh0g

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Suppress warning https://github.com/github/pages-gem/issues/399
github: [metadata]

collections:
  - content_footer
  - content_features
  - content_quotes

# jekyllfaces settings
jekyllfaces:

  brand: Jekyll Faces
  brief: Use Jekyll for your next site.<br/>We'll hyde the scary parts.

  ## unused, maybe something for the future?
  framework: bootstrap # jekyll | bootstrap | skeleton | foundation

  homepage: project # blog | project | soon | webapps

  features:
    - blog     # what 99% of folks will use
    - book     # one or more online books
    - docs     # project documentation
    ## - daily    # a post-a-day site
    - project  # a project or product site
    - soon     # a "coming soon" site
    - webapp   # one or more web applications
    - contributors # one or more authors
    - about    # link to about page

  font_icons: # uncomment the icons sets you would like to use
    - font-awesome # <i class="fa fa-address-book"></i>
    #- foundation # <i class="fi-address-book"></i>
    #- glyphicons # <i class="glyphicon glyphicon-adjust"></i>
    #- icomoon # <i class="icomoon icon-accessibility"></i>
    #- ionicons # <i class="ionicons ion-alert"></i>
    #- material-design # <i class="material-icons">3d_rotation</i>
    #- octicons # <i class="mega-octicon octicon-alert"></i>

  404_page: sticky # badge | dog | droids | glass | link | milk | monster | potty | shrug | sticky | tweet | zork

  search: # valid values are: true | false | {number}
    title:     true # always search
    tags:      true # always search
    keywords:  true # always search
    excerpt:   2000 # only search when fewer than 2001 posts
    inclPages: true # valid values are: true | false

  comments:
    provider: facebook # disqus | facebook | intensedebate | false
    disqus:
      short_name: example
    facebook :
      num_posts: 5
      width: 580
      colorscheme: light # light | dark
    intensedebate :
      account : example

  analytics:
    provider: google # gauges | google | false
    gauges:
      site_id: 'SITE ID'
    google:
      tracking_id: 'UA-123-12'
