# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllfaces
github_username:  groundh0g

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


collections:
  - jekyllfaces
#    output: true

#  tweetHash:     "jaytch #blogs #OSS" # don't hash first tag
#  tweetShoutOut: "GetJaytch"
#
#  footer:
#    col1: "Just Getting Started? | Check out our documentation for <a href='http://moreoncode.com/docs/create-a-blog-in-5-minutes'>Quick Start</a>, | <a href='http://moreoncode.com/docs/faqs'>FAQs</a>, and general information on building | your site and hosting it on <a href='http://moreoncode.com/docs/hosting-on-github-pages'>GitHub Pages</a>."
#    col2: "Found a Bug? | <i class='fa fa-arrow-left'></i> Check the <b>Just Getting Started?</b> section first. | If that doesn't answer your question, head over to| <a href='https://github.com/groundh0g/jaytch/issues/new?title=Short%20Description%20of%20Issue&body=Describe%20in%20detail%20the%20problem%20you%27re%20having.%0D%0DWhat%20steps%20are%20needed%20to%20reproduce%20the%20issue%3F%0D%0DWhat%20did%20you%20expect%20to%20happen%3F%0D%0DWhat%20actually%20happened%3F%0D%0DHow%20did%20that%20make%20you%20feel%3F%0D%0D'>Open an Issue</a> on GitHub."
#    col3: "Feeling Social? | If you'd just like to tell us how awesome we are, | and you're too cheap to buy a round of beers, | you can ping us on <a href='https://twitter.com/GetJaytch'>Twitter</a>!"



jfaces:
  jfaces:
    nav_links: [ # the main menu links at the top of every page
      "Archive|/archive",
      "Categories|/categories",
      "Tags|/tags",
      "Contributors|/contributors",
      "About|/about"
    ]
    sidebar_left:
      sidebars: false # false | ["facebook", "twitter", ...]
    sidebar_right:
      sidebars: ["tagcloud", "posts", "calendar", "countdown", "quote", "quote2", "quote3", "quote4", "twitter"] # false | ["facebook", "twitter", ...]
      columns:  3
      hideForHome: false
      hideForPage: false
      hideForPost: false

#    template: # template is determined by site.layouts_dir (eg. blog, project, book, ...)
#      blog:
#        nav_links: [ # the main menu links at the top of every page
#          "Archive|/archive",
#          "Categories|/categories",
#          "Tags|/tags",
#          "Contributors|/contributors",
#          "About|/about"
#        ]
#        sidebar_left:
#          sidebars: false # false | ["facebook", "twitter", ...]
#        sidebar_right:
#          sidebars: ["tagcloud", "posts", "calendar", "countdown", "quote", "quote2", "quote3", "quote4", "twitter"] # false | ["facebook", "twitter", ...]
#          columns:  3
#          hideForHome: false
#          hideForPage: false
#          hideForPost: false
#
#      book:
#        nav_links: [ # the main menu links at the top of every page
#          "The Book|/index",
#          "The Author|/author",
#          "The Camps|/contributors",
#          "The Blog|/blog",
#          "The Store|/store"
#        ]
#
#      daily:
#        title: Fauxcabulary.org
#        tagline: Fake definitions. Real funny.
#        nav_inverse: true
#        nav_links: [ # the main menu links at the top of every page
#          "Archive|/archive",
#          "Tags|/tags",
#          "Gallery|/gallery",
#          "Commer¢e|/store"
#        ]
#        sidebar_left:
#          sidebars: ["quote", "custom", "tagcloud"] # false | ["facebook", "twitter", ...]
#          columns:  3
#          hideForHome: false
#          hideForPage: true
#          hideForPost: true
#        sidebar_right:
#          sidebars: ["tagcloud", "posts", "calendar", "countdown", "quote", "quote2", "quote3", "quote4", "twitter"] # false | ["facebook", "twitter", ...]
#          columns:  3
#          hideForHome: true
#          hideForPage: false
#          hideForPost: false
#
#      project:
#        title: BYRD
#        tagline: Give'm the BYRD!
#        nav_inverse: true
#        nav_links: [ # the main menu links at the top of every page
#          "Blog &amp; News|/blog",
#          "About|/about",
#          "Contributors|/contributors",
#          [ "Documentation", # dropdown label
#            # dropdown menu items:
#            "Create a Blog in 5 Minutes|/docs/create-a-blog-in-5-minutes",
#            "Configuration Settings Explained|/docs/configuration-settings-explained",
#            "Frameworks, Themes,  &amp; Templates|/docs/layouts-frameworks-themes-and-templates",
#            "Specifying a 404 Page|/docs/specifying-a-404-page",
#            "Sidebars, Widgets, &amp; Snips|/docs/widgets-and-snips",
#            "Using Author Bios|/docs/using-author-bios",
#            "Hosting on GitHub Pages|/docs/hosting-on-github-pages",
#            "---",
#            "Frequently Asked Questions|/docs/faqs"
#          ]
#        ]
#        sidebar_left:
#          sidebars: false # false | ["facebook", "twitter", ...]
#          columns:  3
#          hideForHome: true
#          hideForPage: true
#          hideForPost: false
#        sidebar_right:
#          sidebars: ["posts", "tagcloud"] # false | ["facebook", "twitter", ...]
#          columns:  3
#          hideForHome: true
#          hideForPage: true
#          hideForPost: false
#
#      soon:
#        nav_links: [ # the main menu links at the top of every page
#          "Blog &amp; News|/blog",
#          "The Team|/contributors",
#          "About|/about",
#          "Contact Us|/contact"
#        ]

    sidebars:
      facebook: #https://developers.facebook.com/docs/plugins/page-plugin/
        page:   Fauxcabulary
        title:  Fauxcabulary.org
      facebook2:
        type:  facebook
        page:  Codetopia
      twitter:    # https://twitter.com/settings/widgets/new
        name:     GetJaytch
        widgetId: 709112005668503552
      googleplus: # https://www.kycosoftware.com/code/googleplus-feed-widget-2
        profileId: 113415901204258128457 # +JosephHall_groundh0g
      tagcloud:
        title:   "Tag Cloud"
        maxTags: 20
      author:
        type:  author
      posts:
        type:  posts
        limit: # default 3
        words: # default 15
        showViewPostLink: false
        showArchiveLink: false
        archiveUrl: "/archive"
        category: # default is all
        tag:      # default is all
      quote:
        type: quote
        title:
        quote: # use page's quote
      quote2:
        type: quote
        quote: You can design and create, and build the most wonderful place in the world. But it takes people to make the dream a reality. -- <a href="http://www.brainyquote.com/quotes/authors/w/walt_disney.html">Walt Disney</a>
      quote3:
        type: quote
        quote: Women are like teabags. We don't know our true strength until we are in hot water!
      quote4:
        type: quote
        quote: # use the page's quote
      calendar:
        title: History ...
        date:  # date of most recent post
        width: 100%
      countdown:
        title:    Site Age
        class:    countup
        mode:     inline # block
        datetime: # page.date
      custom:
        type: custom
        path: daily-masthead.md


#  analytics : # settings for analytics, set 'provider' to the analytics provider you want to use
#    provider : google # Set 'provider' to false to turn analytics off entirely
#    gauges :
#        site_id : 'SITE ID'
#    google :
#        tracking_id : 'UA-123-12'
#    googleLegacy :
#        tracking_id : 'UA-123-12'
#    getclicky :
#      site_id :
#    mixpanel :
#        token : '_MIXPANEL_TOKEN_'
#    baidu :
#        token : '_BAIDU_TOKEN_'
#    piwik :
#        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
#        idsite : '1'                   # the id of the site on Piwik

#  comments : # settings for comments helper, set 'provider' to the comment provider you want to use
#    provider : facebook # Set 'provider' to false to turn commenting off entirely
#    disqus :
#      short_name : myname
#    livefyre :
#      site_id : 123
#    intensedebate :
#      account : 123abc
#    facebook :
#      appid : 123
#      num_posts: 5
#      width: 580
#      colorscheme: light
#    duoshuo :
#      short_name : myname
